I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 336, in script
    call screen fable_2_minigame
ScriptError: could not find label 'TimingFailure'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "/Users/akpulaski/Applications/renpy-8.1.0-sdk/renpy/bootstrap.py", line 275, in bootstrap
    renpy.main.main()
  File "/Users/akpulaski/Applications/renpy-8.1.0-sdk/renpy/main.py", line 670, in main
    run(restart)
  File "/Users/akpulaski/Applications/renpy-8.1.0-sdk/renpy/main.py", line 144, in run
    renpy.execution.run_context(True)
  File "/Users/akpulaski/Applications/renpy-8.1.0-sdk/renpy/execution.py", line 953, in run_context
    context.run()
  File "game/script.rpy", line 336, in script
    call screen fable_2_minigame
  File "/Users/akpulaski/Applications/renpy-8.1.0-sdk/renpy/script.py", line 1013, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'TimingFailure'.

macOS-13.4.1-arm64-arm-64bit arm64
Ren'Py 8.1.1.23060707
Dreadfield Stadium 1.0
Fri Jul 21 18:15:45 2023
