I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 617, in script call
    bread "Congratulations, you are the uncontested champion of the Dreadfield Games! You were unstoppable out there."
  File "game/script.rpy", line 733, in script
    call achievementCheck from _call_achievementCheck_9
  File "game/script.rpy", line 740, in <module>
    if cruel >= 3:
AttributeError: type object 'Achievement' has no attribute 'has'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 617, in script call
    bread "Congratulations, you are the uncontested champion of the Dreadfield Games! You were unstoppable out there."
  File "game/script.rpy", line 733, in script
    call achievementCheck from _call_achievementCheck_9
  File "/Users/akpulaski/Applications/renpy-8.1.0-sdk/renpy/ast.py", line 1138, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "/Users/akpulaski/Applications/renpy-8.1.0-sdk/renpy/python.py", line 1122, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 740, in <module>
    if cruel >= 3:
AttributeError: type object 'Achievement' has no attribute 'has'

macOS-13.4.1-arm64-arm-64bit arm64
Ren'Py 8.1.1.23060707
Dreadfield Stadium 1.0
Sun Jul 23 23:19:39 2023
